# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semsec',
            fields=[
                ('ssid', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('sem', models.IntegerField(max_length=2)),
                ('sec', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('usn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=25)),
                ('phone', models.IntegerField(max_length=30)),
                ('Gender', models.CharField(max_length=2)),
            ],
        ),
    ]
