# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semsec',
            name='sec',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='semsec',
            name='sem',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
